In [1]:
import os
import cv2
import numpy as np

In [2]:
image_x,image_y=50,50

In [3]:
def create_folder(folder_name):
    if not os.path.exists(folder_name):
        os.mkdir(folder_name)
    

In [4]:
def store_images(g_id):
    total_pics=1200
    cap=cv2.VideoCapture(0)
    x,y,w,h=300,50,350,350
    #create_folder("C:\\Users\\gauta\\OneDrive\\Desktop\\images\\gestures" +str(g_id))
    create_folder('gesture/' + str(g_id))
    pic_no=0
#flag_start_capturing=False
    flag_start_capturing = True
    frames=0
    while flag_start_capturing==True:
        ret, frame = cap.read()
        frame = cv2.flip(frame,1)
        hsv = cv2.cvtColor(frame,cv2.COLOR_BGR2HSV)
        mask2 = cv2.inRange(hsv,np.array([2,50,60]),np.array([125,150,255]))
        res = cv2.bitwise_and(frame,frame,mask=mask2)
        gray = cv2.cvtColor(res, cv2.COLOR_BGR2GRAY)
        median = cv2.GaussianBlur(gray,(5,5),0)
        kernel_square = np.ones((5,5),np.uint8)
        dilation = cv2.dilate(median, kernel_square,iterations=2)
        opening = cv2.morphologyEx(dilation,cv2.MORPH_CLOSE,kernel_square)
        ret,thresh = cv2.threshold(opening,30,255,cv2.THRESH_BINARY)
        thresh = thresh[y:y+h,x:x+w]
        contours,_ = cv2.findContours(thresh.copy(),cv2.RETR_TREE,cv2.CHAIN_APPROX_NONE)
        if len(contours)>0:
            contour=max(contours,key=cv2.contourArea)
            if cv2.contourArea(contour)>10000 and frames>50:
                x1,y1,w1,h1=cv2.boundingRect(contour)
                pic_no+=1
                save_img=thresh[y1:y1+h1,x1:x1+h1]
                save_img=cv2.resize(save_img,(image_x,image_y))
                cv2.putText(frame,"capturing...,",(30,60),cv2.FONT_HERSHEY_TRIPLEX,2,(127,127,255))
                cv2.imwrite("gesture/"+str(g_id)+"/"+str(pic_no)+".jpg",save_img)
        cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,0),2)
        cv2.putText(frame,str(pic_no),(30,400),cv2.FONT_HERSHEY_TRIPLEX,1.5,(127,127,255))
        cv2.imshow("Capturing gestures",frame)
        cv2.imshow("thresh",thresh)
        keypress=cv2.waitKey(1)
        if keypress == ord('c'):
            if flag_start_capturing == False:
                flag_start_capturing = True
            else:
                flag_start_capturing = False
                frames = 0
            cv2.destroyAllWindows()

        if flag_start_capturing == True:
            frames += 1
        if pic_no == total_pics:
            break


In [5]:
g_id=input("enter the gestures no:")
store_images(g_id)

enter the gestures no:13


In [1]:
from scipy.misc import imread
import numpy as np
import pandas as pd
import os

In [2]:
root='./gesture'

In [3]:
for directory,subdirectories,files in os.walk(root):
    for file in files:
        print(file)
        im=imread(os.path.join(directory,file))
        value=im.flatten()
        value=np.hstack((director[8:],value))
        df=pd.DataFrame(value).T
        df=df.sample(frac=1)
        with open('footest.csv','a')as dataset:
            df.to_csv(dataset,header=False,index=False)

1.jpg


C:\Users\gauta\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.
  after removing the cwd from sys.path.


10.jpg
100.jpg
1000.jpg
1001.jpg
1002.jpg
1003.jpg
1004.jpg
1005.jpg
1006.jpg
1007.jpg
1008.jpg
1009.jpg
101.jpg
1010.jpg
1011.jpg
1012.jpg
1013.jpg
1014.jpg
1015.jpg
1016.jpg
1017.jpg
1018.jpg
1019.jpg
102.jpg
1020.jpg
1021.jpg
1022.jpg
1023.jpg
1024.jpg
1025.jpg
1026.jpg
1027.jpg
1028.jpg
1029.jpg
103.jpg
1030.jpg
1031.jpg
1032.jpg
1033.jpg
1034.jpg
1035.jpg
1036.jpg
1037.jpg
1038.jpg
1039.jpg
104.jpg
1040.jpg
1041.jpg
1042.jpg
1043.jpg
1044.jpg
1045.jpg
1046.jpg
1047.jpg
1048.jpg
1049.jpg
105.jpg
1050.jpg
1051.jpg
1052.jpg
1053.jpg
1054.jpg
1055.jpg
1056.jpg
1057.jpg
1058.jpg
1059.jpg
106.jpg
1060.jpg
1061.jpg
1062.jpg
1063.jpg
1064.jpg
1065.jpg
1066.jpg
1067.jpg
1068.jpg
1069.jpg
107.jpg
1070.jpg
1071.jpg
1072.jpg
1073.jpg
1074.jpg
1075.jpg
1076.jpg
1077.jpg
1078.jpg
1079.jpg
108.jpg
1080.jpg
1081.jpg
1082.jpg
1083.jpg
1084.jpg
1085.jpg
1086.jpg
1087.jpg
1088.jpg
1089.jpg
109.jpg
1090.jpg
1091.jpg
1092.jpg
1093.jpg
1094.jpg
1095.jpg
1096.jpg
1097.jpg
1098.jpg
1099.jpg
11.jpg
110.jp

833.jpg
834.jpg
835.jpg
836.jpg
837.jpg
838.jpg
839.jpg
84.jpg
840.jpg
841.jpg
842.jpg
843.jpg
844.jpg
845.jpg
846.jpg
847.jpg
848.jpg
849.jpg
85.jpg
850.jpg
851.jpg
852.jpg
853.jpg
854.jpg
855.jpg
856.jpg
857.jpg
858.jpg
859.jpg
86.jpg
860.jpg
861.jpg
862.jpg
863.jpg
864.jpg
865.jpg
866.jpg
867.jpg
868.jpg
869.jpg
87.jpg
870.jpg
871.jpg
872.jpg
873.jpg
874.jpg
875.jpg
876.jpg
877.jpg
878.jpg
879.jpg
88.jpg
880.jpg
881.jpg
882.jpg
883.jpg
884.jpg
885.jpg
886.jpg
887.jpg
888.jpg
889.jpg
89.jpg
890.jpg
891.jpg
892.jpg
893.jpg
894.jpg
895.jpg
896.jpg
897.jpg
898.jpg
899.jpg
9.jpg
90.jpg
900.jpg
901.jpg
902.jpg
903.jpg
904.jpg
905.jpg
906.jpg
907.jpg
908.jpg
909.jpg
91.jpg
910.jpg
911.jpg
912.jpg
913.jpg
914.jpg
915.jpg
916.jpg
917.jpg
918.jpg
919.jpg
92.jpg
920.jpg
921.jpg
922.jpg
923.jpg
924.jpg
925.jpg
926.jpg
927.jpg
928.jpg
929.jpg
93.jpg
930.jpg
931.jpg
932.jpg
933.jpg
934.jpg
935.jpg
936.jpg
937.jpg
938.jpg
939.jpg
94.jpg
940.jpg
941.jpg
942.jpg
943.jpg
944.jpg
945.jpg
946.jpg
947.j

672.jpg
673.jpg
674.jpg
675.jpg
676.jpg
677.jpg
678.jpg
679.jpg
68.jpg
680.jpg
681.jpg
682.jpg
683.jpg
684.jpg
685.jpg
686.jpg
687.jpg
688.jpg
689.jpg
69.jpg
690.jpg
691.jpg
692.jpg
693.jpg
694.jpg
695.jpg
696.jpg
697.jpg
698.jpg
699.jpg
7.jpg
70.jpg
700.jpg
701.jpg
702.jpg
703.jpg
704.jpg
705.jpg
706.jpg
707.jpg
708.jpg
709.jpg
71.jpg
710.jpg
711.jpg
712.jpg
713.jpg
714.jpg
715.jpg
716.jpg
717.jpg
718.jpg
719.jpg
72.jpg
720.jpg
721.jpg
722.jpg
723.jpg
724.jpg
725.jpg
726.jpg
727.jpg
728.jpg
729.jpg
73.jpg
730.jpg
731.jpg
732.jpg
733.jpg
734.jpg
735.jpg
736.jpg
737.jpg
738.jpg
739.jpg
74.jpg
740.jpg
741.jpg
742.jpg
743.jpg
744.jpg
745.jpg
746.jpg
747.jpg
748.jpg
749.jpg
75.jpg
750.jpg
751.jpg
752.jpg
753.jpg
754.jpg
755.jpg
756.jpg
757.jpg
758.jpg
759.jpg
76.jpg
760.jpg
761.jpg
762.jpg
763.jpg
764.jpg
765.jpg
766.jpg
767.jpg
768.jpg
769.jpg
77.jpg
770.jpg
771.jpg
772.jpg
773.jpg
774.jpg
775.jpg
776.jpg
777.jpg
778.jpg
779.jpg
78.jpg
780.jpg
781.jpg
782.jpg
783.jpg
784.jpg
785.jpg
786.j

509.jpg
51.jpg
510.jpg
511.jpg
512.jpg
513.jpg
514.jpg
515.jpg
516.jpg
517.jpg
518.jpg
519.jpg
52.jpg
520.jpg
521.jpg
522.jpg
523.jpg
524.jpg
525.jpg
526.jpg
527.jpg
528.jpg
529.jpg
53.jpg
530.jpg
531.jpg
532.jpg
533.jpg
534.jpg
535.jpg
536.jpg
537.jpg
538.jpg
539.jpg
54.jpg
540.jpg
541.jpg
542.jpg
543.jpg
544.jpg
545.jpg
546.jpg
547.jpg
548.jpg
549.jpg
55.jpg
550.jpg
551.jpg
552.jpg
553.jpg
554.jpg
555.jpg
556.jpg
557.jpg
558.jpg
559.jpg
56.jpg
560.jpg
561.jpg
562.jpg
563.jpg
564.jpg
565.jpg
566.jpg
567.jpg
568.jpg
569.jpg
57.jpg
570.jpg
571.jpg
572.jpg
573.jpg
574.jpg
575.jpg
576.jpg
577.jpg
578.jpg
579.jpg
58.jpg
580.jpg
581.jpg
582.jpg
583.jpg
584.jpg
585.jpg
586.jpg
587.jpg
588.jpg
589.jpg
59.jpg
590.jpg
591.jpg
592.jpg
593.jpg
594.jpg
595.jpg
596.jpg
597.jpg
598.jpg
599.jpg
6.jpg
60.jpg
600.jpg
601.jpg
602.jpg
603.jpg
604.jpg
605.jpg
606.jpg
607.jpg
608.jpg
609.jpg
61.jpg
610.jpg
611.jpg
612.jpg
613.jpg
614.jpg
615.jpg
616.jpg
617.jpg
618.jpg
619.jpg
62.jpg
620.jpg
621.jpg
622.jp

342.jpg
343.jpg
344.jpg
345.jpg
346.jpg
347.jpg
348.jpg
349.jpg
35.jpg
350.jpg
351.jpg
352.jpg
353.jpg
354.jpg
355.jpg
356.jpg
357.jpg
358.jpg
359.jpg
36.jpg
360.jpg
361.jpg
362.jpg
363.jpg
364.jpg
365.jpg
366.jpg
367.jpg
368.jpg
369.jpg
37.jpg
370.jpg
371.jpg
372.jpg
373.jpg
374.jpg
375.jpg
376.jpg
377.jpg
378.jpg
379.jpg
38.jpg
380.jpg
381.jpg
382.jpg
383.jpg
384.jpg
385.jpg
386.jpg
387.jpg
388.jpg
389.jpg
39.jpg
390.jpg
391.jpg
392.jpg
393.jpg
394.jpg
395.jpg
396.jpg
397.jpg
398.jpg
399.jpg
4.jpg
40.jpg
400.jpg
401.jpg
402.jpg
403.jpg
404.jpg
405.jpg
406.jpg
407.jpg
408.jpg
409.jpg
41.jpg
410.jpg
411.jpg
412.jpg
413.jpg
414.jpg
415.jpg
416.jpg
417.jpg
418.jpg
419.jpg
42.jpg
420.jpg
421.jpg
422.jpg
423.jpg
424.jpg
425.jpg
426.jpg
427.jpg
428.jpg
429.jpg
43.jpg
430.jpg
431.jpg
432.jpg
433.jpg
434.jpg
435.jpg
436.jpg
437.jpg
438.jpg
439.jpg
44.jpg
440.jpg
441.jpg
442.jpg
443.jpg
444.jpg
445.jpg
446.jpg
447.jpg
448.jpg
449.jpg
45.jpg
450.jpg
451.jpg
452.jpg
453.jpg
454.jpg
455.jpg
456.j

176.jpg
177.jpg
178.jpg
179.jpg
18.jpg
180.jpg
181.jpg
182.jpg
183.jpg
184.jpg
185.jpg
186.jpg
187.jpg
188.jpg
189.jpg
19.jpg
190.jpg
191.jpg
192.jpg
193.jpg
194.jpg
195.jpg
196.jpg
197.jpg
198.jpg
199.jpg
2.jpg
20.jpg
200.jpg
201.jpg
202.jpg
203.jpg
204.jpg
205.jpg
206.jpg
207.jpg
208.jpg
209.jpg
21.jpg
210.jpg
211.jpg
212.jpg
213.jpg
214.jpg
215.jpg
216.jpg
217.jpg
218.jpg
219.jpg
22.jpg
220.jpg
221.jpg
222.jpg
223.jpg
224.jpg
225.jpg
226.jpg
227.jpg
228.jpg
229.jpg
23.jpg
230.jpg
231.jpg
232.jpg
233.jpg
234.jpg
235.jpg
236.jpg
237.jpg
238.jpg
239.jpg
24.jpg
240.jpg
241.jpg
242.jpg
243.jpg
244.jpg
245.jpg
246.jpg
247.jpg
248.jpg
249.jpg
25.jpg
250.jpg
251.jpg
252.jpg
253.jpg
254.jpg
255.jpg
256.jpg
257.jpg
258.jpg
259.jpg
26.jpg
260.jpg
261.jpg
262.jpg
263.jpg
264.jpg
265.jpg
266.jpg
267.jpg
268.jpg
269.jpg
27.jpg
270.jpg
271.jpg
272.jpg
273.jpg
274.jpg
275.jpg
276.jpg
277.jpg
278.jpg
279.jpg
28.jpg
280.jpg
281.jpg
282.jpg
283.jpg
284.jpg
285.jpg
286.jpg
287.jpg
288.jpg
289.jpg
29.jp

1106.jpg
1107.jpg
1108.jpg
1109.jpg
111.jpg
1110.jpg
1111.jpg
1112.jpg
1113.jpg
1114.jpg
1115.jpg
1116.jpg
1117.jpg
1118.jpg
1119.jpg
112.jpg
1120.jpg
1121.jpg
1122.jpg
1123.jpg
1124.jpg
1125.jpg
1126.jpg
1127.jpg
1128.jpg
1129.jpg
113.jpg
1130.jpg
1131.jpg
1132.jpg
1133.jpg
1134.jpg
1135.jpg
1136.jpg
1137.jpg
1138.jpg
1139.jpg
114.jpg
1140.jpg
1141.jpg
1142.jpg
1143.jpg
1144.jpg
1145.jpg
1146.jpg
1147.jpg
1148.jpg
1149.jpg
115.jpg
1150.jpg
1151.jpg
1152.jpg
1153.jpg
1154.jpg
1155.jpg
1156.jpg
1157.jpg
1158.jpg
1159.jpg
116.jpg
1160.jpg
1161.jpg
1162.jpg
1163.jpg
1164.jpg
1165.jpg
1166.jpg
1167.jpg
1168.jpg
1169.jpg
117.jpg
1170.jpg
1171.jpg
1172.jpg
1173.jpg
1174.jpg
1175.jpg
1176.jpg
1177.jpg
1178.jpg
1179.jpg
118.jpg
1180.jpg
1181.jpg
1182.jpg
1183.jpg
1184.jpg
1185.jpg
1186.jpg
1187.jpg
1188.jpg
1189.jpg
119.jpg
1190.jpg
1191.jpg
1192.jpg
1193.jpg
1194.jpg
1195.jpg
1196.jpg
1197.jpg
1198.jpg
1199.jpg
12.jpg
120.jpg
1200.jpg
121.jpg
122.jpg
123.jpg
124.jpg
125.jpg
126.jpg
127.jpg
12

957.jpg
958.jpg
959.jpg
96.jpg
960.jpg
961.jpg
962.jpg
963.jpg
964.jpg
965.jpg
966.jpg
967.jpg
968.jpg
969.jpg
97.jpg
970.jpg
971.jpg
972.jpg
973.jpg
974.jpg
975.jpg
976.jpg
977.jpg
978.jpg
979.jpg
98.jpg
980.jpg
981.jpg
982.jpg
983.jpg
984.jpg
985.jpg
986.jpg
987.jpg
988.jpg
989.jpg
99.jpg
990.jpg
991.jpg
992.jpg
993.jpg
994.jpg
995.jpg
996.jpg
997.jpg
998.jpg
999.jpg
1.jpg
10.jpg
100.jpg
1000.jpg
1001.jpg
1002.jpg
1003.jpg
1004.jpg
1005.jpg
1006.jpg
1007.jpg
1008.jpg
1009.jpg
101.jpg
1010.jpg
1011.jpg
1012.jpg
1013.jpg
1014.jpg
1015.jpg
1016.jpg
1017.jpg
1018.jpg
1019.jpg
102.jpg
1020.jpg
1021.jpg
1022.jpg
1023.jpg
1024.jpg
1025.jpg
1026.jpg
1027.jpg
1028.jpg
1029.jpg
103.jpg
1030.jpg
1031.jpg
1032.jpg
1033.jpg
1034.jpg
1035.jpg
1036.jpg
1037.jpg
1038.jpg
1039.jpg
104.jpg
1040.jpg
1041.jpg
1042.jpg
1043.jpg
1044.jpg
1045.jpg
1046.jpg
1047.jpg
1048.jpg
1049.jpg
105.jpg
1050.jpg
1051.jpg
1052.jpg
1053.jpg
1054.jpg
1055.jpg
1056.jpg
1057.jpg
1058.jpg
1059.jpg
106.jpg
1060.jpg
1061.jpg
1

788.jpg
789.jpg
79.jpg
790.jpg
791.jpg
792.jpg
793.jpg
794.jpg
795.jpg
796.jpg
797.jpg
798.jpg
799.jpg
8.jpg
80.jpg
800.jpg
801.jpg
802.jpg
803.jpg
804.jpg
805.jpg
806.jpg
807.jpg
808.jpg
809.jpg
81.jpg
810.jpg
811.jpg
812.jpg
813.jpg
814.jpg
815.jpg
816.jpg
817.jpg
818.jpg
819.jpg
82.jpg
820.jpg
821.jpg
822.jpg
823.jpg
824.jpg
825.jpg
826.jpg
827.jpg
828.jpg
829.jpg
83.jpg
830.jpg
831.jpg
832.jpg
833.jpg
834.jpg
835.jpg
836.jpg
837.jpg
838.jpg
839.jpg
84.jpg
840.jpg
841.jpg
842.jpg
843.jpg
844.jpg
845.jpg
846.jpg
847.jpg
848.jpg
849.jpg
85.jpg
850.jpg
851.jpg
852.jpg
853.jpg
854.jpg
855.jpg
856.jpg
857.jpg
858.jpg
859.jpg
86.jpg
860.jpg
861.jpg
862.jpg
863.jpg
864.jpg
865.jpg
866.jpg
867.jpg
868.jpg
869.jpg
87.jpg
870.jpg
871.jpg
872.jpg
873.jpg
874.jpg
875.jpg
876.jpg
877.jpg
878.jpg
879.jpg
88.jpg
880.jpg
881.jpg
882.jpg
883.jpg
884.jpg
885.jpg
886.jpg
887.jpg
888.jpg
889.jpg
89.jpg
890.jpg
891.jpg
892.jpg
893.jpg
894.jpg
895.jpg
896.jpg
897.jpg
898.jpg
899.jpg
9.jpg
90.jpg
900.jpg


618.jpg
619.jpg
62.jpg
620.jpg
621.jpg
622.jpg
623.jpg
624.jpg
625.jpg
626.jpg
627.jpg
628.jpg
629.jpg
63.jpg
630.jpg
631.jpg
632.jpg
633.jpg
634.jpg
635.jpg
636.jpg
637.jpg
638.jpg
639.jpg
64.jpg
640.jpg
641.jpg
642.jpg
643.jpg
644.jpg
645.jpg
646.jpg
647.jpg
648.jpg
649.jpg
65.jpg
650.jpg
651.jpg
652.jpg
653.jpg
654.jpg
655.jpg
656.jpg
657.jpg
658.jpg
659.jpg
66.jpg
660.jpg
661.jpg
662.jpg
663.jpg
664.jpg
665.jpg
666.jpg
667.jpg
668.jpg
669.jpg
67.jpg
670.jpg
671.jpg
672.jpg
673.jpg
674.jpg
675.jpg
676.jpg
677.jpg
678.jpg
679.jpg
68.jpg
680.jpg
681.jpg
682.jpg
683.jpg
684.jpg
685.jpg
686.jpg
687.jpg
688.jpg
689.jpg
69.jpg
690.jpg
691.jpg
692.jpg
693.jpg
694.jpg
695.jpg
696.jpg
697.jpg
698.jpg
699.jpg
7.jpg
70.jpg
700.jpg
701.jpg
702.jpg
703.jpg
704.jpg
705.jpg
706.jpg
707.jpg
708.jpg
709.jpg
71.jpg
710.jpg
711.jpg
712.jpg
713.jpg
714.jpg
715.jpg
716.jpg
717.jpg
718.jpg
719.jpg
72.jpg
720.jpg
721.jpg
722.jpg
723.jpg
724.jpg
725.jpg
726.jpg
727.jpg
728.jpg
729.jpg
73.jpg
730.jpg
731.jp

451.jpg
452.jpg
453.jpg
454.jpg
455.jpg
456.jpg
457.jpg
458.jpg
459.jpg
46.jpg
460.jpg
461.jpg
462.jpg
463.jpg
464.jpg
465.jpg
466.jpg
467.jpg
468.jpg
469.jpg
47.jpg
470.jpg
471.jpg
472.jpg
473.jpg
474.jpg
475.jpg
476.jpg
477.jpg
478.jpg
479.jpg
48.jpg
480.jpg
481.jpg
482.jpg
483.jpg
484.jpg
485.jpg
486.jpg
487.jpg
488.jpg
489.jpg
49.jpg
490.jpg
491.jpg
492.jpg
493.jpg
494.jpg
495.jpg
496.jpg
497.jpg
498.jpg
499.jpg
5.jpg
50.jpg
500.jpg
501.jpg
502.jpg
503.jpg
504.jpg
505.jpg
506.jpg
507.jpg
508.jpg
509.jpg
51.jpg
510.jpg
511.jpg
512.jpg
513.jpg
514.jpg
515.jpg
516.jpg
517.jpg
518.jpg
519.jpg
52.jpg
520.jpg
521.jpg
522.jpg
523.jpg
524.jpg
525.jpg
526.jpg
527.jpg
528.jpg
529.jpg
53.jpg
530.jpg
531.jpg
532.jpg
533.jpg
534.jpg
535.jpg
536.jpg
537.jpg
538.jpg
539.jpg
54.jpg
540.jpg
541.jpg
542.jpg
543.jpg
544.jpg
545.jpg
546.jpg
547.jpg
548.jpg
549.jpg
55.jpg
550.jpg
551.jpg
552.jpg
553.jpg
554.jpg
555.jpg
556.jpg
557.jpg
558.jpg
559.jpg
56.jpg
560.jpg
561.jpg
562.jpg
563.jpg
564.jpg
565.j

291.jpg
292.jpg
293.jpg
294.jpg
295.jpg
296.jpg
297.jpg
298.jpg
299.jpg
3.jpg
30.jpg
300.jpg
301.jpg
302.jpg
303.jpg
304.jpg
305.jpg
306.jpg
307.jpg
308.jpg
309.jpg
31.jpg
310.jpg
311.jpg
312.jpg
313.jpg
314.jpg
315.jpg
316.jpg
317.jpg
318.jpg
319.jpg
32.jpg
320.jpg
321.jpg
322.jpg
323.jpg
324.jpg
325.jpg
326.jpg
327.jpg
328.jpg
329.jpg
33.jpg
330.jpg
331.jpg
332.jpg
333.jpg
334.jpg
335.jpg
336.jpg
337.jpg
338.jpg
339.jpg
34.jpg
340.jpg
341.jpg
342.jpg
343.jpg
344.jpg
345.jpg
346.jpg
347.jpg
348.jpg
349.jpg
35.jpg
350.jpg
351.jpg
352.jpg
353.jpg
354.jpg
355.jpg
356.jpg
357.jpg
358.jpg
359.jpg
36.jpg
360.jpg
361.jpg
362.jpg
363.jpg
364.jpg
365.jpg
366.jpg
367.jpg
368.jpg
369.jpg
37.jpg
370.jpg
371.jpg
372.jpg
373.jpg
374.jpg
375.jpg
376.jpg
377.jpg
378.jpg
379.jpg
38.jpg
380.jpg
381.jpg
382.jpg
383.jpg
384.jpg
385.jpg
386.jpg
387.jpg
388.jpg
389.jpg
39.jpg
390.jpg
391.jpg
392.jpg
393.jpg
394.jpg
395.jpg
396.jpg
397.jpg
398.jpg
399.jpg
4.jpg
40.jpg
400.jpg
401.jpg
402.jpg
403.jpg
404.jpg

In [3]:
import numpy as np
from keras.layers import Dense,Flatten,Conv2D
from keras.layers import MaxPooling2D,Dropout
from keras.utils import np_utils,print_summary
from keras.models import Sequential
from keras.callbacks import ModelCheckpoint
import pandas as pd
import keras.backend as K


Using TensorFlow backend.


In [4]:
dataset=pd.read_csv('footest.csv')
print(dataset.shape)

(11999, 2501)


In [5]:
newdata=np.array(dataset)
#np.random.shuffle(newdata)
print(newdata)

[['e\\1' 1 0 ... 0 0 0]
 ['e\\1' 0 0 ... 0 0 0]
 ['e\\1' 0 0 ... 0 0 0]
 ...
 ['e\\9' 0 1 ... 0 0 0]
 ['e\\9' 0 4 ... 0 0 0]
 ['e\\9' 0 2 ... 0 0 0]]


In [6]:
lab=newdata[:,0]
info=newdata[:,1:2501]
info=info/255

In [7]:
print(info.shape)
print(info)
print(lab.shape)
print(lab)

(11999, 2500)
[[0.00392156862745098 0.0 0.00392156862745098 ... 0.0 0.0 0.0]
 [0.0 0.0 0.00392156862745098 ... 0.0 0.0 0.0]
 [0.0 0.0 0.0 ... 0.0 0.0 0.0]
 ...
 [0.0 0.00392156862745098 0.0 ... 0.0 0.0 0.0]
 [0.0 0.01568627450980392 0.0 ... 0.0 0.0 0.0]
 [0.0 0.00784313725490196 0.0 ... 0.0 0.0 0.0]]
(11999,)
['e\\1' 'e\\1' 'e\\1' ... 'e\\9' 'e\\9' 'e\\9']


In [8]:
unique=np.unique(lab)
print(unique)

['e\\1' 'e\\10' 'e\\2' 'e\\3' 'e\\4' 'e\\5' 'e\\6' 'e\\7' 'e\\8' 'e\\9']


In [9]:
dic={}
j=0
for i in unique:
    dic[i]=j
    j=j+1

In [10]:
print(dic)

{'e\\1': 0, 'e\\10': 1, 'e\\2': 2, 'e\\3': 3, 'e\\4': 4, 'e\\5': 5, 'e\\6': 6, 'e\\7': 7, 'e\\8': 8, 'e\\9': 9}


In [11]:
m=0
for i in lab:
    lab[m]=dic[i]
    m=m+1

In [12]:
print(lab)

[0 0 0 ... 9 9 9]


In [13]:
from keras.utils import to_categorical

In [14]:
Ny = len(np.unique(lab)) 
print(Ny)

10


In [15]:
lab = to_categorical(lab[:], num_classes = Ny)

In [16]:
print(lab)
print(lab.shape)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]
(11999, 10)


In [17]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [18]:
X_train, X_test, Y_train, Y_test = train_test_split(info, lab, test_size = 0.20, random_state = 1)


In [19]:
print(X_train.shape)
print(X_test.shape)

(9599, 2500)
(2400, 2500)


In [20]:
X_test=X_test.reshape(2400,50,50,1)
print(X_test.shape)
X_train=X_train.reshape(9599,50,50,1)
print(X_train.shape)

(2400, 50, 50, 1)
(9599, 50, 50, 1)


In [29]:
print(Y_train.shape)
print(Y_test.shape)

(9599, 10)
(2400, 10)


In [21]:
print(Y_test.shape[1])
print(image_x)

10
50


In [31]:
from keras.callbacks import ModelCheckpoint
def keras_model(image_x,image_y):
    num_of_classes=10
    model=Sequential()
    model.add(Conv2D(32,(5,5),input_shape=(image_x,image_y,1),activation='relu'))
    model.add(MaxPooling2D(pool_size=(2,2),strides=(2,2),padding='same'))
    model.add(Conv2D(64,(5,5),activation='sigmoid'))
    model.add(MaxPooling2D(pool_size=(5,5),strides=(5,5),padding='same'))
    model.add(Flatten())
    model.add(Dense(1024,activation='relu'))
    model.add(Dropout(0.2))
    model.add(Dense(num_of_classes,activation='softmax'))
    model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
    filepath="HandEmoji.h5"
    checkpoint1=ModelCheckpoint(filepath,monitor='val_acc',verbose=1,save_best_only=True,mode='max')
    callbacks_list=[checkpoint1]
    return model,callbacks_list
    
    

In [32]:
model, callbacks_list=keras_model(image_x,image_y)
model.fit(X_train,Y_train,validation_data=(X_test,Y_test),epochs=10,callbacks=callbacks_list,batch_size=64)
scores=model.evaluate(X_test,Y_test,verbose=0)
print("cnn Error: %.2f%%"%(100-scores[1]*100))
print_summary(model)
model.save('HandEmoji.h5')

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Instructions for updating:
Use tf.cast instead.
Train on 9599 samples, validate on 2400 samples
Epoch 1/10
9599/9599 [==============================] - 49s 5ms/step - loss: 0.7666 - acc: 0.7742 - val_loss: 0.1545 - val_acc: 0.9621

Epoch 00001: val_acc improved from -inf to 0.96208, saving model to HandEmoji.h5
Epoch 2/10
9599/9599 [==============================] - 48s 5ms/step - loss: 0.1432 - acc: 0.9598 - val_loss: 0.0993 - val_acc: 0.9729

Epoch 00002: val_acc improved from 0.96208 to 0.97292, saving model to HandEmoji.h5
Epoch 3/10
9599/9599 [==============================] - 59s 6ms/step - loss: 0.1017 - acc: 0.9708 - val_loss: 0.0941 - val_acc: 0.9725

Epoch 00003: val_acc did not improve from 0.97292
Epoch 4/10
9599/9599 [==============================] - 49s 5ms/step - loss: 0.0878 - acc: 0.9

In [6]:
import cv2
from keras.models import load_model
import numpy as np
import os


Using TensorFlow backend.


In [7]:
model = load_model('HandEmoji.h5')

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Instructions for updating:
Use tf.cast instead.


In [8]:
def main():
    emojis = get_emojis()
    cap = cv2.VideoCapture(0)
    x, y, w, h = 300, 50, 350, 350

    while (cap.isOpened()):
        ret, img = cap.read()
        img = cv2.flip(img, 1)
        hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
        mask2 = cv2.inRange(hsv, np.array([2, 50, 60]), np.array([25, 150, 255]))
        res = cv2.bitwise_and(img, img, mask=mask2)
        gray = cv2.cvtColor(res, cv2.COLOR_BGR2GRAY)
        median = cv2.GaussianBlur(gray, (5, 5), 0)

        kernel_square = np.ones((5, 5), np.uint8)
        dilation = cv2.dilate(median, kernel_square, iterations=2)
        opening = cv2.morphologyEx(dilation, cv2.MORPH_CLOSE, kernel_square)
        ret, thresh = cv2.threshold(opening, 30, 255, cv2.THRESH_BINARY)

        thresh = thresh[y:y + h, x:x + w]
        contours = cv2.findContours(thresh.copy(), cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)[0]
        if len(contours) > 0:
            contour = max(contours, key=cv2.contourArea)
            if cv2.contourArea(contour) > 2500:
                x, y, w1, h1 = cv2.boundingRect(contour)
                newImage = thresh[y:y + h1, x:x + w1]
                newImage = cv2.resize(newImage, (50, 50))
                pred_probab, pred_class = keras_predict(model, newImage)
                print(pred_class, pred_probab)
                img = overlay(img, emojis[pred_class], 400, 250, 90, 90)

        x, y, w, h = 300, 50, 350, 350
        cv2.imshow("Frame", img)
        cv2.imshow("Contours", thresh)
        k = cv2.waitKey(10)
        if k == 27:
            break

In [9]:
def keras_predict(model,image):
    processed=keras_process_image(image)
    pred_probab=model.predict(processed)[0]
    pred_class=list(pred_probab).index(max(pred_probab))
    return max(pred_probab),pred_class
    

def keras_process_image(img):
    image_x = 50
    image_y = 50
    img = cv2.resize(img, (image_x, image_y))
    img = np.array(img, dtype=np.float32)
    img = np.reshape(img, (-1, image_x, image_y, 1))
    return img


In [10]:
def get_emojis():
    emojis_folder = 'hand_emo/'
    emojis = []
    for emoji in range(len(os.listdir(emojis_folder))):
        print(emoji)
        emojis.append(cv2.imread(emojis_folder+str(emoji)+'.png', -1))
    return emojis

In [11]:
def overlay(image, emoji, x,y,w,h):
    emoji = cv2.resize(emoji, (w, h))
    try:
        image[y:y+h, x:x+w] = blend_transparent(image[y:y+h, x:x+w], emoji)
    except:
        pass
    return image

def blend_transparent(face_img, overlay_t_img):
    # Split out the transparency mask from the colour info
    overlay_img = overlay_t_img[:,:,:3] # Grab the BRG planes
    overlay_mask = overlay_t_img[:,:,3:]  # And the alpha plane

    # Again calculate the inverse mask
    background_mask = 255 - overlay_mask

    # Turn the masks into three channel, so we can use them as weights
    overlay_mask = cv2.cvtColor(overlay_mask, cv2.COLOR_GRAY2BGR)
    background_mask = cv2.cvtColor(background_mask, cv2.COLOR_GRAY2BGR)

    # Create a masked out face image, and masked out overlay
    # We convert the images to floating point in range 0.0 - 1.0
    face_part = (face_img * (1 / 255.0)) * (background_mask * (1 / 255.0))
    overlay_part = (overlay_img * (1 / 255.0)) * (overlay_mask * (1 / 255.0))

    # And finally just add them together, and rescale it back to an 8bit integer image
    return np.uint8(cv2.addWeighted(face_part, 255.0, overlay_part, 255.0, 0.0))

keras_predict(model, np.zeros((50, 50, 1), dtype=np.uint8))
main()

0
1
2
3
4
5
6
7
8
9
10
11
12
5 0.76264954
9 0.9994092
9 0.99637884
6 0.97941256
6 0.8234337
3 0.6499197
6 0.94404316
1 0.9624338
6 0.45213538
9 0.5813519
1 0.7691911
6 0.9330846
3 0.9643613
1 0.95620394
6 0.48329097
6 0.52469003
6 0.8144944
6 0.87258065
3 0.5778481
6 0.7496744
6 0.4206463
6 0.5556034
1 0.55048656
3 0.7404777
6 0.97688246
6 0.45927724
6 0.4361734
6 0.65947556
6 0.4506547
9 0.48072594
3 0.93070346
6 0.5490173
9 0.9960924
9 0.634547
6 0.8087822
9 0.71366304
6 0.6977122
3 0.7245794
6 0.82379234
5 0.80965924
3 0.96826136
3 0.718679
3 0.718679
9 0.6388567
6 0.8903304
5 0.7732163
3 0.8094721
6 0.92634785
1 0.9960367
9 0.99944764
0 0.82541996
0 0.9868615
1 0.94616264
1 0.89918363
6 0.8943184
9 0.9233695
8 0.6171243
6 0.9553538
6 0.5177303
0 0.96569085
6 0.94882655
1 0.9785759
1 0.9785759
0 0.9996369
1 0.9842546
9 0.83069974
5 0.57244796
5 0.8643977
1 0.9862998
5 0.8622602
3 0.6274058
3 0.99737406
3 0.99737406
3 0.9965064
3 0.34688023
7 0.5115537
1 0.5449839
1 0.44754672
4 0.43

2 0.9814291
2 0.96561927
2 0.98636276
2 0.9907051
2 0.99955815
2 0.9986482
2 0.9764717
2 0.99943906
2 0.9940936
2 0.9994387
2 0.9982085
2 0.9991424
2 0.97633445
2 0.97633445
2 0.9700734
2 0.9997793
2 0.9993642
2 0.99883026
2 0.9851407
2 0.9705828
2 0.9982821
2 0.99920136
2 0.6468487
2 0.9868133
2 0.9868133
2 0.9965502
2 0.9981906
2 0.99251854
2 0.999276
2 0.999534
2 0.963155
2 0.9914761
2 0.95880204
2 0.99953854
2 0.9937692
2 0.9852116
2 0.9911874
2 0.9996493
2 0.99559313
2 0.9990243
2 0.9939622
2 0.75703853
2 0.99758315
2 0.97959137
2 0.9989943
2 0.99763834
2 0.9991622
2 0.9863268
2 0.99684334
2 0.9968449
2 0.9923915
2 0.89550453
2 0.9959254
2 0.9586363
2 0.9981383
2 0.96242666
2 0.88943005
2 0.9936923
2 0.99855214
2 0.9661204
2 0.99512035
2 0.9467426
2 0.9944845
2 0.9902181
2 0.7958375
2 0.9995241
2 0.9812375
2 0.9952502
2 0.9975395
2 0.9988153
2 0.9973598
2 0.9937668
2 0.9810951
2 0.99005145
2 0.9932272
2 0.9867649
2 0.96435034
2 0.989035
2 0.929771
2 0.9921537
2 0.99886274
2 0.9896

6 0.31440517
6 0.36788502
9 0.5616171
9 0.67805105
9 0.68378663
9 0.74235034
9 0.8894545
9 0.8894545
1 0.39901793
9 0.6443446
6 0.44913223
4 0.8655787
1 0.67999727
9 0.6462013
6 0.9961868
9 0.5319265
9 0.9177184
9 0.9177184
1 0.91826916
1 0.91826916
9 0.9981609
9 0.9981609
9 0.986188
9 0.892015
9 0.96782726
5 0.6996257
9 0.99885976
9 0.93779606
1 0.99989855
1 0.9999783
1 0.86473113
1 0.99561995
1 0.9882464
1 0.9834336
1 0.9550464
1 0.95769167
6 0.94476587
6 0.48757493
6 0.48757493
1 0.9391439
7 0.74296814
7 0.80042887
1 0.9885225
1 0.9931774
1 0.99695635
1 0.9460187
9 0.995706
9 0.99639916
9 0.98757684
9 0.98757684
9 0.99101526
9 0.9974348
9 0.9924779
1 0.57390445
1 0.99980694
1 0.9989825
1 0.9997352
1 0.9995493
1 0.96697056
1 0.97111976
1 0.97111976
1 0.99681985
7 0.7779545
7 0.9889214
1 0.9042497
1 0.9928213
1 0.9981115
1 0.9956182
1 0.969374
1 0.75640404
1 0.75640404
1 0.98564446
7 0.9747376
7 0.56624126
1 0.4085998
1 0.9765738
1 0.3781022
9 0.58295274
1 0.7155941
9 0.4946354
4 0.77

9 0.47295043
9 0.47295043
1 0.5782919
1 0.72841895
1 0.72841895
9 0.49770248
9 0.49770248
9 0.49788988
9 0.49788988
1 0.6809115
1 0.6809115
9 0.43814856
9 0.43814856
1 0.93326485
1 0.93326485
1 0.48951507
1 0.48951507
1 0.4686702
1 0.4686702
9 0.5012676
9 0.5012676
9 0.21067104
9 0.21067104
1 0.34842652
1 0.34842652
7 0.23313117
7 0.23313117
1 0.29041216
1 0.29041216
1 0.7490512
1 0.7490512
3 0.9237233
3 0.9237233
7 0.96692485
7 0.96692485
7 0.9854354
7 0.9854354
7 0.53395534
7 0.53395534
9 0.61213166
9 0.61213166
1 0.63069546
1 0.63069546
1 0.9621328


error: OpenCV(4.1.1) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'
